from __future__ import annotations

from quant_platform_kit.strategy_contracts import StrategyManifest

from us_equity_strategies.ai_extensions import build_default_ai_extension_config
from us_equity_strategies.income_layer_defaults import income_layer_default_config

GLOBAL_ETF_CONFIDENCE_VOL_GATE_PROFILE = "global_etf_confidence_vol_gate"
RUSSELL_TOP50_LEADER_ROTATION_PROFILE = "russell_top50_leader_rotation"
NASDAQ_SP500_SMART_DCA_PROFILE = "nasdaq_sp500_smart_dca"
IBIT_SMART_DCA_PROFILE = "ibit_smart_dca"


def _manifest(
    *,
    profile: str,
    display_name: str,
    description: str,
    aliases: tuple[str, ...] = (),
    required_inputs: frozenset[str] = frozenset(),
    default_config: dict[str, object] | None = None,
) -> StrategyManifest:
    return StrategyManifest(
        profile=profile,
        domain="us_equity",
        display_name=display_name,
        description=description,
        aliases=aliases,
        required_inputs=required_inputs,
        default_config=default_config or {},
    )


global_etf_rotation_manifest = _manifest(
    profile="global_etf_rotation",
    display_name="Global ETF Rotation",
    description=(
        "Quarterly top-2 global ETF rotation with daily canary defense, SMA250 confidence gating, and BIL safe haven."
    ),
    aliases=("global_macro_etf_rotation", GLOBAL_ETF_CONFIDENCE_VOL_GATE_PROFILE),
    required_inputs=frozenset({"feature_snapshot"}),
    default_config={
        "ranking_pool": (
            "EWY",
            "EWT",
            "INDA",
            "FXI",
            "EWJ",
            "VGK",
            "VOO",
            "XLK",
            "SMH",
            "GLD",
            "SLV",
            "USO",
            "DBA",
            "XLE",
            "XLF",
            "ITA",
            "XLP",
            "XLU",
            "XLV",
            "IHI",
            "VNQ",
            "KRE",
        ),
        "canary_assets": ("SPY", "EFA", "EEM", "AGG"),
        "safe_haven": "BIL",
        "top_n": 2,
        "hold_bonus": 0.02,
        "canary_bad_threshold": 4,
        "rebalance_months": (3, 6, 9, 12),
        "sma_period": 250,
        "confidence_weighting_enabled": True,
        "confidence_metric": "z_gap",
        "confidence_threshold": 1.0,
        "confidence_top1_weight": 0.75,
        "confidence_volatility_gate_enabled": True,
        "confidence_volatility_window": 126,
        "confidence_volatility_max_ratio": 1.3,
        **income_layer_default_config("global_etf_rotation"),
        "market_regime_control_enabled": True,
        "market_regime_control_apply_risk_reduced": False,
        "market_regime_control_apply_risk_off": False,
        "market_regime_control_risk_reduced_scalar": 0.50,
        "market_regime_control_risk_off_scalar": 0.0,
    },
)

tqqq_growth_income_manifest = _manifest(
    profile="tqqq_growth_income",
    display_name="TQQQ Growth Income",
    description="QQQ-signal TQQQ/QQQM dual-drive growth profile with BOXX/cash defense and additive income sleeve.",
    aliases=(),
    required_inputs=frozenset({"benchmark_history", "portfolio_snapshot"}),
    default_config={
        "benchmark_symbol": "QQQ",
        "managed_symbols": ("TQQQ", "QQQM", "BOXX", "SCHD", "DGRO", "SGOV", "SPYI", "QQQI"),
        "income_threshold_usd": 250000.0,
        "qqqi_income_ratio": 0.10,
        "cash_reserve_ratio": 0.02,
        "rebalance_threshold_ratio": 0.01,
        "execution_cash_reserve_ratio": 0.0,
        **income_layer_default_config("tqqq_growth_income"),
        "option_growth_overlay_enabled": True,
        "option_growth_overlay_recipe": "tqqq_leaps_growth_v1",
        "option_growth_overlay_start_usd": 250000.0,
        "option_growth_overlay_nav_budget_ratio": 0.03,
        "attack_allocation_mode": "fixed_qqq_tqqq_pullback",
        "dual_drive_qqq_weight": 0.45,
        "dual_drive_tqqq_weight": 0.45,
        "dual_drive_unlevered_symbol": "QQQM",
        "dual_drive_cash_reserve_ratio": 0.02,
        "dual_drive_allow_pullback": True,
        "dual_drive_require_ma20_slope": True,
        "dual_drive_pullback_rebound_window": 20,
        "dual_drive_pullback_rebound_threshold_mode": "volatility_scaled",
        "dual_drive_pullback_rebound_threshold": 0.0,
        "dual_drive_pullback_rebound_volatility_multiplier": 2.0,
        "dual_drive_volatility_delever_enabled": True,
        "dual_drive_volatility_delever_window": 5,
        "dual_drive_volatility_delever_threshold": 0.28,
        "dual_drive_volatility_delever_exit_threshold": 0.28,
        "dual_drive_volatility_delever_threshold_mode": "rolling_percentile",
        "dual_drive_volatility_delever_dynamic_lookback": 252,
        "dual_drive_volatility_delever_dynamic_percentile": 0.90,
        "dual_drive_volatility_delever_dynamic_min_periods": 126,
        "dual_drive_volatility_delever_dynamic_floor": 0.24,
        "dual_drive_volatility_delever_dynamic_cap": 0.36,
        "dual_drive_volatility_delever_taco_veto_enabled": True,
        "dual_drive_volatility_delever_retention_mode": "environment",
        "dual_drive_volatility_delever_retention_ratio": 0.0,
        "dual_drive_volatility_delever_retention_policy": "tqqq_step_softzero_0.25_0.50",
        "dual_drive_volatility_delever_retention_context_required": True,
        "dual_drive_volatility_delever_max_retention_ratio": 0.50,
        "dual_drive_crisis_defense_enabled": True,
        "market_regime_control_enabled": True,
        "ai_extensions": build_default_ai_extension_config(),
    },
)

soxl_soxx_trend_income_manifest = _manifest(
    profile="soxl_soxx_trend_income",
    display_name="SOXL/SOXX Semiconductor Trend Income",
    description="SOXL / SOXX semiconductor trend switch with BOXX parking and additive income sleeve.",
    aliases=(),
    required_inputs=frozenset({"derived_indicators", "portfolio_snapshot"}),
    default_config={
        "managed_symbols": ("SOXL", "SOXX", "BOXX", "SCHD", "DGRO", "SGOV", "SPYI", "QQQI"),
        "trend_ma_window": 140,
        "cash_reserve_ratio": 0.03,
        "min_trade_ratio": 0.01,
        "min_trade_floor": 100.0,
        "rebalance_threshold_ratio": 0.01,
        **income_layer_default_config("soxl_soxx_trend_income"),
        "option_income_overlay_enabled": True,
        "option_income_overlay_recipe": "soxx_put_credit_spread_income_v1",
        "option_income_overlay_start_usd": 1000000.0,
        "option_income_overlay_nav_risk_ratio": 0.01,
        "trend_entry_buffer": 0.08,
        "trend_mid_buffer": 0.06,
        "trend_exit_buffer": 0.02,
        "attack_allocation_mode": "soxx_gate_tiered_blend",
        "blend_gate_trend_source": "SOXX",
        "blend_gate_soxl_weight": 0.70,
        "blend_gate_mid_soxl_weight": 0.65,
        "blend_gate_active_soxx_weight": 0.20,
        "blend_gate_defensive_soxx_weight": 0.15,
        "blend_gate_rsi_cap_enabled": True,
        "blend_gate_rsi_threshold": 70.0,
        "blend_gate_dynamic_rsi_threshold_enabled": True,
        "blend_gate_bollinger_cap_enabled": True,
        "blend_gate_overlay_stack_triggers": True,
        "blend_gate_volatility_delever_enabled": True,
        "blend_gate_volatility_delever_symbol": "SOXX",
        "blend_gate_volatility_delever_window": 10,
        "blend_gate_volatility_delever_threshold": 0.55,
        "blend_gate_volatility_delever_threshold_mode": "rolling_percentile",
        "blend_gate_volatility_delever_dynamic_lookback": 252,
        "blend_gate_volatility_delever_dynamic_percentile": 0.95,
        "blend_gate_volatility_delever_dynamic_min_periods": 126,
        "blend_gate_volatility_delever_dynamic_floor": 0.50,
        "blend_gate_volatility_delever_dynamic_cap": 0.75,
        "blend_gate_volatility_delever_retention_ratio": 0.0,
        "blend_gate_volatility_delever_retention_mode": "environment",
        "blend_gate_volatility_delever_retention_policy": "soxl_step_rebound_0.25_0.50",
        "blend_gate_volatility_delever_retention_context_required": True,
        "blend_gate_volatility_delever_max_retention_ratio": 0.50,
        "blend_gate_volatility_delever_redirect_symbol": "SOXX",
        "market_regime_control_enabled": True,
        "market_regime_control_apply_risk_reduced": False,
        "market_regime_control_apply_risk_off": True,
    },
)

russell_top50_leader_rotation_manifest = _manifest(
    profile=RUSSELL_TOP50_LEADER_ROTATION_PROFILE,
    display_name="Russell Top50 Leader Rotation",
    description="Balanced monthly Russell Top50 leader rotation using a fixed 50% Top2 / 50% Top4 sleeve blend and no trend de-risking by default.",
    aliases=(),
    required_inputs=frozenset({"feature_snapshot"}),
    default_config={
        "benchmark_symbol": "QQQ",
        "broad_benchmark_symbol": "SPY",
        "safe_haven": "BOXX",
        "dynamic_universe_size": 50,
        "blend_sleeves": (
            {"name": "top2_cap50", "weight": 0.50, "holdings_count": 2, "single_name_cap": 0.50},
            {"name": "top4_cap25", "weight": 0.50, "holdings_count": 4, "single_name_cap": 0.25},
        ),
        "holdings_count": 4,
        "single_name_cap": 0.25,
        "min_position_value_usd": 3000.0,
        "hold_buffer": 2,
        "hold_bonus": 0.10,
        "risk_on_exposure": 1.0,
        "soft_defense_exposure": 1.0,
        "hard_defense_exposure": 1.0,
        "soft_breadth_threshold": 0.0,
        "hard_breadth_threshold": 0.0,
        "min_adv20_usd": 20000000.0,
        "runtime_execution_window_trading_days": 3,
        "execution_cash_reserve_ratio": 0.0,
        **income_layer_default_config(RUSSELL_TOP50_LEADER_ROTATION_PROFILE),
        "option_growth_overlay_enabled": True,
        "option_growth_overlay_recipe": "qqq_leaps_growth_v1",
        "option_growth_overlay_start_usd": 1000000.0,
        "option_growth_overlay_nav_budget_ratio": 0.03,
        "market_regime_control_enabled": True,
        "market_regime_control_apply_risk_reduced": False,
        "market_regime_control_apply_risk_off": False,
        "market_regime_control_risk_reduced_scalar": 0.50,
        "market_regime_control_risk_off_scalar": 0.0,
    },
)

nasdaq_sp500_smart_dca_manifest = _manifest(
    profile=NASDAQ_SP500_SMART_DCA_PROFILE,
    display_name="Nasdaq 100 / S&P 500 Smart DCA",
    description="Buy-only Nasdaq 100 and S&P 500 fixed-amount DCA profile with optional smart sizing gates.",
    aliases=(),
    required_inputs=frozenset({"market_history", "portfolio_snapshot"}),
    default_config={
        "signal_symbols": ("QQQ", "SPY"),
        "trade_allocations": {
            "QQQM": 0.50,
            "SPLG": 0.50,
        },
        "managed_symbols": ("QQQM", "SPLG"),
        "base_investment_usd": 1000.0,
        "max_investment_usd": None,
        "cash_reserve_usd": 0.0,
        "min_investment_usd": 5.0,
        "investment_amount_mode": "fixed",
        "smart_multiplier_enabled": False,
        "cadence": "monthly",
        "monthly_day": 25,
        "monthly_window_calendar_days": 5,
        "weekly_day": 4,
        "weekly_window_calendar_days": 4,
        "quarterly_months": (1, 4, 7, 10),
        "quarterly_day": 25,
        "quarterly_window_calendar_days": 5,
        "mild_drawdown_threshold": 0.08,
        "deep_drawdown_threshold": 0.15,
        "severe_drawdown_threshold": 0.25,
        "mild_discount_gap": 0.05,
        "deep_discount_gap": 0.10,
        "expensive_gap": 0.12,
        "very_expensive_gap": 0.20,
        "shallow_drawdown_threshold": 0.03,
        "overbought_rsi": 70.0,
        "base_multiplier": 1.0,
        "mild_pullback_multiplier": 1.10,
        "deep_pullback_multiplier": 1.25,
        "severe_pullback_multiplier": 1.50,
        "expensive_multiplier": 1.0,
        "very_expensive_multiplier": 1.0,
        "execution_cash_reserve_ratio": 0.0,
        "execution_rebalance_threshold_ratio": 0.0,
    },
)

ibit_smart_dca_manifest = _manifest(
    profile=IBIT_SMART_DCA_PROFILE,
    display_name="IBIT Smart DCA",
    description="Buy-only spot Bitcoin ETF DCA profile with optional pullback-aware smart sizing.",
    aliases=("bitcoin_etf_smart_dca",),
    required_inputs=frozenset({"derived_indicators", "portfolio_snapshot"}),
    default_config={
        "signal_symbols": ("BTC-USD",),
        "trade_allocations": {
            "IBIT": 1.0,
        },
        "managed_symbols": ("IBIT",),
        "base_investment_usd": 1000.0,
        "max_investment_usd": None,
        "cash_reserve_usd": 0.0,
        "min_investment_usd": 5.0,
        "investment_amount_mode": "fixed",
        "smart_multiplier_enabled": False,
        "cadence": "monthly",
        "monthly_day": 25,
        "monthly_window_calendar_days": 5,
        "weekly_day": 4,
        "weekly_window_calendar_days": 4,
        "quarterly_months": (1, 4, 7, 10),
        "quarterly_day": 25,
        "quarterly_window_calendar_days": 5,
        "mild_drawdown_threshold": 0.12,
        "deep_drawdown_threshold": 0.25,
        "severe_drawdown_threshold": 0.40,
        "mild_discount_gap": 0.08,
        "deep_discount_gap": 0.18,
        "expensive_gap": 0.30,
        "very_expensive_gap": 0.60,
        "shallow_drawdown_threshold": 0.05,
        "overbought_rsi": 75.0,
        "base_multiplier": 1.0,
        "mild_pullback_multiplier": 1.50,
        "deep_pullback_multiplier": 2.25,
        "severe_pullback_multiplier": 3.0,
        "expensive_multiplier": 1.0,
        "very_expensive_multiplier": 1.0,
        "cycle_indicator_enabled": True,
        "ahr999_bottom_threshold": 0.45,
        "ahr999_accumulation_threshold": 0.80,
        "ahr999_dca_threshold": 1.20,
        "ahr999_bottom_multiplier": 3.0,
        "ahr999_accumulation_multiplier": 2.25,
        "ahr999_dca_multiplier": 1.50,
        "ahr999_expensive_multiplier": 0.0,
        "execution_cash_reserve_ratio": 0.0,
        "execution_rebalance_threshold_ratio": 0.0,
    },
)

MANIFESTS = {
    global_etf_rotation_manifest.profile: global_etf_rotation_manifest,
    tqqq_growth_income_manifest.profile: tqqq_growth_income_manifest,
    soxl_soxx_trend_income_manifest.profile: soxl_soxx_trend_income_manifest,
    russell_top50_leader_rotation_manifest.profile: russell_top50_leader_rotation_manifest,
    nasdaq_sp500_smart_dca_manifest.profile: nasdaq_sp500_smart_dca_manifest,
    ibit_smart_dca_manifest.profile: ibit_smart_dca_manifest,
}

MANIFEST_ALIASES = {
    str(alias).strip().lower(): manifest.profile
    for manifest in MANIFESTS.values()
    for alias in manifest.aliases
}


def get_strategy_manifest(profile: str) -> StrategyManifest:
    normalized = str(profile or "").strip().lower()
    return MANIFESTS[MANIFEST_ALIASES.get(normalized, normalized)]


__all__ = [
    "MANIFESTS",
    "get_strategy_manifest",
    "global_etf_rotation_manifest",
    "tqqq_growth_income_manifest",
    "soxl_soxx_trend_income_manifest",
    "russell_top50_leader_rotation_manifest",
    "nasdaq_sp500_smart_dca_manifest",
    "ibit_smart_dca_manifest",
]
